### PR TITLE
Upgrade to PHP 7.1

### PR DESCRIPTION
**Pull request by tannerjfco**
## The Problem:
drud/ddev#330 OP - Update to PHP 7.1

## The Fix:
This PR makes the necessary changes to facilitate update to PHP 7.1 in the local web container. It also moves the php package install from drud/docker.php7 into this dockerfile, allowing us to deprecate that repo/image. 

## The Test:

This container can be tested with ddev by setting a site's webimage tag to `drud/nginx-php-fpm-local:v0.7.4-3-gfa8ceef`

## Release/Deployment notes:

- Upon merge, a new v0.8.0 tag should be created and pushed to git
- Upon merge, a new v0.8.0 tag should be created and pushed to docker hub
- Update ddev PR with new v0.8.0 tag

### CODE REVIEW

**Comment by rfay** [comment]
I took the liberty of rebasing this.

**Comment by rfay** [comment]
I tested this in the following environments by adding `webimage: drud/nginx-php-fpm7-local:v0.7.4-4-g14dff80` to my .ddev/config.yml:

* d8 composer-built install: It worked and did not require the workaround of adding a php5.6 constraint to the config stanza of the config.json.
* Standard d7 site, clicked around, tried some things.

It doesn't appear right now that we'll break much by moving to 7.1

**Comment by tannerjfco** [comment]
Thanks @rfay , I've done the following:

- dropped the '7' from the dockerhub repo name
- moved php package installs in here, so we can drop drud/docker.php7
- moved things from /usr/bin to /usr/local/bin

**Comment by rfay** [comment]
Gave it another spin, scanned through the changes again. LGTM. Thanks!

**Comment by rfay** [comment]
Oops, one or two last tiny requests (which can be ignored if you like)
* Change the 'rm' of php7.1 php.ini to `rm -f`
* Make the PHP version a Make variable in the Makefile.

**Comment by rfay** [comment]
Appears the PHP_VERSION in the Dockerfile isn't used everywhere. I was trying it out, it's probably not worth the effort right now, but it would sure be nice if this could be built multiple ways.

If we wanted that to work, probably the PHP_VERSION should just be the numeric part, like 7.1, and should be used in
```
RUN rm /etc/php/7.1/cli/php.ini && \
    ln -s /etc/php/7.1/fpm/php.ini /etc/php/7.1/cli/php.ini && \
    mkdir -p /etc/nginx/sites-enabled && \
    touch /var/log/php-fpm.log && \
    chown nginx:nginx /var/log/php-fpm.log && \
    chown -R nginx:nginx /var/run && \
    touch /var/log/nginx/access.log && \
    touch /var/log/nginx/error.log && \
    chown -R nginx:nginx /var/log/nginx/ && \
    mkdir -p /var/lib/nginx/logs && \
    touch /var/lib/nginx/logs/error.log && \
    chown nginx:nginx /var/lib/nginx/logs/error.log && \
    chmod ugo+x /usr/local/bin/* && \
    chmod ugo+x /start.sh
```

But all that wasn't a goal here. I was just trying it out.

**Pull request merged**
